added basic test file
if you clone the repo, run the install script, and then run: 
~/Git/OpenFlexTyper/build/./flextyper index -r test.fq.gz --gz -c -o . -x test 
Then you should get:
processed fasta file   ./test.fasta
ERROR: File "" does not exist. Exit.

Which is where I am stopping for dinner